        <script type="text/javascript" src="PERCH_LOGINPATH/plugins/editors/markitup/jquery.markitup.pack.js"></script>
        <script type="text/javascript" src="PERCH_LOGINPATH/plugins/editors/markitup/settings.js"></script>
        <script type="text/javascript" src="PERCH_LOGINPATH/plugins/editors/markitup/config.js"></script>
        <link rel="stylesheet" href="PERCH_LOGINPATH/plugins/editors/markitup/skin.css" type="text/css" />
        <link rel="stylesheet" href="PERCH_LOGINPATH/plugins/editors/markitup/style.css" type="text/css" />